# todo branche
name: Publish to Nexus
on:
  push:
    branches:
      - migrate-javax-to-jakarta
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "nexus-stemys",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: show current directory
        run: pwd
      - name: Deploy to Nexus
        run: mvn deploy -s file:/home/runner/work/rsql-jpa/rsql-jpa/.github/settings.xml